/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package pizzariadaclau;

import java.util.Random;
import javax.swing.JOptionPane;
/**
 *
 * @author Andre
 */
public class InterfacePizza extends javax.swing.JFrame {
    static String borda;
    static String azeitona;
    static int cont = 0;
    static String stpizzaid1, stpizzaid2, stpizzaid3, stpizzaid4, stpizzaid5;
    static boolean condApagar = false;
    
    /**
     * Creates new form InterfacePizza
     */
    public InterfacePizza() {
        initComponents();
        setTitle("PIZZARIA DA CLAU");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        Titulo = new javax.swing.JLabel();
        jPanelBorda = new javax.swing.JPanel();
        jLabelAzeitona = new javax.swing.JLabel();
        jPanelSabor = new javax.swing.JPanel();
        jLabelSabor = new javax.swing.JLabel();
        jPanelBorda1 = new javax.swing.JPanel();
        jLabelBorda = new javax.swing.JLabel();
        jPanelBorda2 = new javax.swing.JPanel();
        jLabelFormato = new javax.swing.JLabel();
        jPanelBorda3 = new javax.swing.JPanel();
        jLabelPreco = new javax.swing.JLabel();
        jButtonAdicionar1 = new javax.swing.JButton();
        jPanelID = new javax.swing.JPanel();
        jLabelID = new javax.swing.JLabel();
        jTextFieldID = new javax.swing.JTextField();
        jTextFieldSabor = new javax.swing.JTextField();
        jTextFieldPreco = new javax.swing.JTextField();
        jTextFieldFormato1 = new javax.swing.JTextField();
        jPanelBorda22 = new javax.swing.JPanel();
        jLabelRecheio = new javax.swing.JLabel();
        jCheckBoxRecheioTRUE = new javax.swing.JCheckBox();
        jLabelRecheio2 = new javax.swing.JLabel();
        jCheckBoxRecheioFALSE = new javax.swing.JCheckBox();
        jPanelBorda23 = new javax.swing.JPanel();
        jLabelAzeitona11 = new javax.swing.JLabel();
        jCheckBoxAzeitonaTRUE = new javax.swing.JCheckBox();
        jLabelRecheio3 = new javax.swing.JLabel();
        jCheckBoxAzeitonaFALSE = new javax.swing.JCheckBox();
        jComboBoxApagar = new javax.swing.JComboBox<>();
        jComboBoxEditar = new javax.swing.JComboBox<>();
        jComboBoxMostrarDados = new javax.swing.JComboBox<>();
        jScrollPane1 = new javax.swing.JScrollPane();
        taAvisos = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        Titulo.setFont(new java.awt.Font("Comic Sans MS", 0, 36)); // NOI18N
        Titulo.setText("PIZZA MAKER");

        jPanelBorda.setBackground(new java.awt.Color(255, 255, 255));

        jLabelAzeitona.setBackground(new java.awt.Color(255, 255, 255));
        jLabelAzeitona.setFont(new java.awt.Font("Comic Sans MS", 0, 20)); // NOI18N
        jLabelAzeitona.setText("AZEITONA");

        javax.swing.GroupLayout jPanelBordaLayout = new javax.swing.GroupLayout(jPanelBorda);
        jPanelBorda.setLayout(jPanelBordaLayout);
        jPanelBordaLayout.setHorizontalGroup(
            jPanelBordaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelBordaLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabelAzeitona)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanelBordaLayout.setVerticalGroup(
            jPanelBordaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelBordaLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabelAzeitona)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanelSabor.setBackground(new java.awt.Color(255, 255, 255));

        jLabelSabor.setFont(new java.awt.Font("Comic Sans MS", 0, 20)); // NOI18N
        jLabelSabor.setText("SABOR");

        javax.swing.GroupLayout jPanelSaborLayout = new javax.swing.GroupLayout(jPanelSabor);
        jPanelSabor.setLayout(jPanelSaborLayout);
        jPanelSaborLayout.setHorizontalGroup(
            jPanelSaborLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelSaborLayout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(jLabelSabor)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanelSaborLayout.setVerticalGroup(
            jPanelSaborLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelSaborLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabelSabor)
                .addContainerGap())
        );

        jPanelBorda1.setBackground(new java.awt.Color(255, 255, 255));

        jLabelBorda.setBackground(new java.awt.Color(255, 255, 255));
        jLabelBorda.setFont(new java.awt.Font("Comic Sans MS", 0, 20)); // NOI18N
        jLabelBorda.setText("BORDA");

        javax.swing.GroupLayout jPanelBorda1Layout = new javax.swing.GroupLayout(jPanelBorda1);
        jPanelBorda1.setLayout(jPanelBorda1Layout);
        jPanelBorda1Layout.setHorizontalGroup(
            jPanelBorda1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelBorda1Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(jLabelBorda, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanelBorda1Layout.setVerticalGroup(
            jPanelBorda1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelBorda1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabelBorda)
                .addContainerGap())
        );

        jPanelBorda2.setBackground(new java.awt.Color(255, 255, 255));

        jLabelFormato.setBackground(new java.awt.Color(255, 255, 255));
        jLabelFormato.setFont(new java.awt.Font("Comic Sans MS", 0, 20)); // NOI18N
        jLabelFormato.setText("FORMATO");

        javax.swing.GroupLayout jPanelBorda2Layout = new javax.swing.GroupLayout(jPanelBorda2);
        jPanelBorda2.setLayout(jPanelBorda2Layout);
        jPanelBorda2Layout.setHorizontalGroup(
            jPanelBorda2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelBorda2Layout.createSequentialGroup()
                .addContainerGap(12, Short.MAX_VALUE)
                .addComponent(jLabelFormato)
                .addGap(18, 18, 18))
        );
        jPanelBorda2Layout.setVerticalGroup(
            jPanelBorda2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelBorda2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabelFormato, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jPanelBorda3.setBackground(new java.awt.Color(255, 255, 255));

        jLabelPreco.setBackground(new java.awt.Color(255, 255, 255));
        jLabelPreco.setFont(new java.awt.Font("Comic Sans MS", 0, 20)); // NOI18N
        jLabelPreco.setText("PREÇO");

        javax.swing.GroupLayout jPanelBorda3Layout = new javax.swing.GroupLayout(jPanelBorda3);
        jPanelBorda3.setLayout(jPanelBorda3Layout);
        jPanelBorda3Layout.setHorizontalGroup(
            jPanelBorda3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelBorda3Layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addComponent(jLabelPreco)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanelBorda3Layout.setVerticalGroup(
            jPanelBorda3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelBorda3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabelPreco)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jButtonAdicionar1.setFont(new java.awt.Font("Comic Sans MS", 0, 18)); // NOI18N
        jButtonAdicionar1.setText("Adicionar");
        jButtonAdicionar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAdicionar1ActionPerformed(evt);
            }
        });

        jPanelID.setBackground(new java.awt.Color(255, 255, 255));

        jLabelID.setBackground(new java.awt.Color(255, 255, 255));
        jLabelID.setFont(new java.awt.Font("Comic Sans MS", 0, 18)); // NOI18N
        jLabelID.setText("ID gerado:");

        jTextFieldID.setEditable(false);

        javax.swing.GroupLayout jPanelIDLayout = new javax.swing.GroupLayout(jPanelID);
        jPanelID.setLayout(jPanelIDLayout);
        jPanelIDLayout.setHorizontalGroup(
            jPanelIDLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelIDLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabelID, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextFieldID, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(22, Short.MAX_VALUE))
        );
        jPanelIDLayout.setVerticalGroup(
            jPanelIDLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelIDLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelIDLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabelID, javax.swing.GroupLayout.DEFAULT_SIZE, 28, Short.MAX_VALUE)
                    .addComponent(jTextFieldID))
                .addContainerGap())
        );

        jPanelBorda22.setBackground(new java.awt.Color(255, 255, 255));

        jLabelRecheio.setBackground(new java.awt.Color(255, 255, 255));
        jLabelRecheio.setFont(new java.awt.Font("Comic Sans MS", 0, 18)); // NOI18N
        jLabelRecheio.setText("RECHEADA");

        jCheckBoxRecheioTRUE.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBoxRecheioTRUEActionPerformed(evt);
            }
        });

        jLabelRecheio2.setBackground(new java.awt.Color(255, 255, 255));
        jLabelRecheio2.setFont(new java.awt.Font("Comic Sans MS", 0, 18)); // NOI18N
        jLabelRecheio2.setText("|  SEM RECHEIO");

        jCheckBoxRecheioFALSE.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBoxRecheioFALSEActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanelBorda22Layout = new javax.swing.GroupLayout(jPanelBorda22);
        jPanelBorda22.setLayout(jPanelBorda22Layout);
        jPanelBorda22Layout.setHorizontalGroup(
            jPanelBorda22Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelBorda22Layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(jLabelRecheio)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jCheckBoxRecheioTRUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabelRecheio2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jCheckBoxRecheioFALSE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanelBorda22Layout.setVerticalGroup(
            jPanelBorda22Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelBorda22Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelBorda22Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jCheckBoxRecheioTRUE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabelRecheio2, javax.swing.GroupLayout.DEFAULT_SIZE, 28, Short.MAX_VALUE)
                    .addComponent(jCheckBoxRecheioFALSE, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabelRecheio))
                .addContainerGap())
        );

        jPanelBorda23.setBackground(new java.awt.Color(255, 255, 255));

        jLabelAzeitona11.setBackground(new java.awt.Color(255, 255, 255));
        jLabelAzeitona11.setFont(new java.awt.Font("Comic Sans MS", 0, 14)); // NOI18N
        jLabelAzeitona11.setText("COM AZEITONA");

        jCheckBoxAzeitonaTRUE.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBoxAzeitonaTRUEActionPerformed(evt);
            }
        });

        jLabelRecheio3.setBackground(new java.awt.Color(255, 255, 255));
        jLabelRecheio3.setFont(new java.awt.Font("Comic Sans MS", 0, 18)); // NOI18N
        jLabelRecheio3.setText("|  SEM AZEITONA");

        jCheckBoxAzeitonaFALSE.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBoxAzeitonaFALSEActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanelBorda23Layout = new javax.swing.GroupLayout(jPanelBorda23);
        jPanelBorda23.setLayout(jPanelBorda23Layout);
        jPanelBorda23Layout.setHorizontalGroup(
            jPanelBorda23Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelBorda23Layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(jLabelAzeitona11)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jCheckBoxAzeitonaTRUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabelRecheio3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jCheckBoxAzeitonaFALSE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanelBorda23Layout.setVerticalGroup(
            jPanelBorda23Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelBorda23Layout.createSequentialGroup()
                .addGap(8, 8, 8)
                .addComponent(jLabelAzeitona11, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addComponent(jCheckBoxAzeitonaTRUE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jLabelRecheio3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jCheckBoxAzeitonaFALSE, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jComboBoxApagar.setFont(new java.awt.Font("Comic Sans MS", 0, 14)); // NOI18N
        jComboBoxApagar.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Apagar", "Pizza 1", "Pizza 2", "Pizza 3", "Pizza 4", "Pizza 5" }));
        jComboBoxApagar.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jComboBoxApagarFocusGained(evt);
            }
        });
        jComboBoxApagar.addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                jComboBoxApagarComponentShown(evt);
            }
        });
        jComboBoxApagar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxApagarActionPerformed(evt);
            }
        });

        jComboBoxEditar.setFont(new java.awt.Font("Comic Sans MS", 0, 14)); // NOI18N
        jComboBoxEditar.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Editar", "Pizza 1", "Pizza 2", "Pizza 3", "Pizza 4", "Pizza 5" }));
        jComboBoxEditar.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jComboBoxEditarFocusGained(evt);
            }
        });
        jComboBoxEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxEditarActionPerformed(evt);
            }
        });

        jComboBoxMostrarDados.setFont(new java.awt.Font("Comic Sans MS", 0, 14)); // NOI18N
        jComboBoxMostrarDados.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Visualizar", "Pizza 1", "Pizza 2", "Pizza 3", "Pizza 4", "Pizza 5" }));
        jComboBoxMostrarDados.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jComboBoxMostrarDadosFocusGained(evt);
            }
        });

        taAvisos.setEditable(false);
        taAvisos.setColumns(20);
        taAvisos.setFont(new java.awt.Font("Comic Sans MS", 0, 14)); // NOI18N
        taAvisos.setRows(5);
        jScrollPane1.setViewportView(taAvisos);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jComboBoxEditar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jComboBoxMostrarDados, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(36, 36, 36)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanelSabor, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanelBorda1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanelBorda3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanelBorda2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanelBorda, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButtonAdicionar1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jTextFieldFormato1)
                    .addComponent(jTextFieldPreco)
                    .addComponent(jPanelBorda23, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(Titulo)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jPanelBorda22, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jTextFieldSabor)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jPanelID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jComboBoxApagar, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(Titulo, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(33, 33, 33)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jPanelSabor, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jTextFieldSabor))
                            .addComponent(jComboBoxEditar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jPanelBorda22, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jPanelBorda23, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jPanelBorda1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jPanelBorda, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addComponent(jScrollPane1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTextFieldFormato1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanelBorda2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jPanelBorda3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextFieldPreco, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(30, 30, 30))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jComboBoxMostrarDados, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(68, 68, 68)))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jComboBoxApagar)
                    .addComponent(jPanelID, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButtonAdicionar1, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE))
                .addGap(49, 49, 49))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 51, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    
    public void apagarCampos(){
        jTextFieldSabor.setText("");
        if (jCheckBoxRecheioTRUE.isSelected()){
            jCheckBoxRecheioTRUE.setSelected(false);
        }
        if (jCheckBoxRecheioFALSE.isSelected()) {
            jCheckBoxRecheioFALSE.setSelected(false);
        }
        if (jCheckBoxAzeitonaTRUE.isSelected()){
            jCheckBoxAzeitonaTRUE.setSelected(false);
        }
        if (jCheckBoxAzeitonaFALSE.isSelected()){
            jCheckBoxAzeitonaFALSE.setSelected(false);
        }
        jTextFieldFormato1.setText("");
        jTextFieldPreco.setText("");
    }
    
    private void jCheckBoxRecheioFALSEActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBoxRecheioFALSEActionPerformed
        borda = "borda sem recheio";
        if (jCheckBoxRecheioTRUE.isSelected()){
            jCheckBoxRecheioTRUE.setSelected(false);
        }
    }//GEN-LAST:event_jCheckBoxRecheioFALSEActionPerformed

    private void jCheckBoxAzeitonaFALSEActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBoxAzeitonaFALSEActionPerformed
        azeitona = "sem azeitona";
        if (jCheckBoxAzeitonaTRUE.isSelected()){
            jCheckBoxAzeitonaTRUE.setSelected(false);
        }
    }//GEN-LAST:event_jCheckBoxAzeitonaFALSEActionPerformed

    private void jButtonAdicionar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAdicionar1ActionPerformed
        Random numid = new Random();
        if (jTextFieldSabor.getText().length() != 0 && (jCheckBoxRecheioTRUE.isSelected() || jCheckBoxRecheioFALSE.isSelected())
                && (jCheckBoxAzeitonaTRUE.isSelected() || jCheckBoxAzeitonaFALSE.isSelected()) && jTextFieldFormato1.getText().length() != 0
                && jTextFieldPreco.getText().length() != 0 && jTextFieldPreco.getText().matches("^[0-9]*$")) {
            if (cont < ListaPizza.pizzas.length) {
                ListaPizza.pizzas[cont] = new Pizza(jTextFieldSabor.getText(), borda, jTextFieldPreco.getText(), azeitona,
                        jTextFieldFormato1.getText());
                ListaPizza.pizzas[cont].setId(numid.nextInt((10000 - 1000) + 1) + 100);
                String idstring = Integer.toString(ListaPizza.pizzas[cont].getId());
                jTextFieldID.setText(idstring);
                System.out.println(ListaPizza.pizzas[cont].toString());
                condApagar = true;
                taAvisos.setText("pizza " + (cont + 1) + " adicionada!");
                cont++;
                apagarCampos();
            } else {
                taAvisos.setText("Numero total atingido!\nredefinindo a ultima pizza...\npizza 5 adicionada!");
                ListaPizza.pizzas[4] = new Pizza(jTextFieldSabor.getText(), borda, jTextFieldPreco.getText(), azeitona,
                        jTextFieldFormato1.getText());
                ListaPizza.pizzas[4].setId(numid.nextInt((10000 - 1000) + 1) + 100);
                String idstring2 = Integer.toString(ListaPizza.pizzas[4].getId());
                jTextFieldID.setText(idstring2);
                System.out.println(ListaPizza.pizzas[4].toString());
                condApagar = true;
                apagarCampos();
            }
        }
        else {
            JOptionPane.showMessageDialog(jPanel1, "valores invalidos! tente novamente preenchendo todos os campos de forma correta!", "AVISO!", JOptionPane.WARNING_MESSAGE);
        }
        //ListaPizza.pizzas[0] = new Pizza(jTextFieldSabor.getText(), marcacaoborda, jTextFieldPreco.getText(), marcacaoazeitona,
        //jTextFieldFormato1.getText()); 
        //for (int i = 0; i < 5; i++){
           // if (ListaPizza.pizzas.length < 6){
           //         ListaPizza.pizzas[i].sabor = jTextFieldSabor.getText();
           // }
        //}
    }//GEN-LAST:event_jButtonAdicionar1ActionPerformed

    private void jCheckBoxRecheioTRUEActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBoxRecheioTRUEActionPerformed
        borda = "borda recheada";
        if (jCheckBoxRecheioFALSE.isSelected()){
            jCheckBoxRecheioFALSE.setSelected(false);
        }
    }//GEN-LAST:event_jCheckBoxRecheioTRUEActionPerformed

    private void jCheckBoxAzeitonaTRUEActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBoxAzeitonaTRUEActionPerformed
        azeitona = "com azeitona";
        if (jCheckBoxAzeitonaFALSE.isSelected()) {
            jCheckBoxAzeitonaFALSE.setSelected(false);
        }
    }//GEN-LAST:event_jCheckBoxAzeitonaTRUEActionPerformed

    
    public void mensagemApagar(){
        taAvisos.setText("Pizza removida com sucesso!");
    }
    
    private void jComboBoxApagarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxApagarActionPerformed
        inserirObjeto();
        if (jComboBoxApagar.getSelectedIndex() == 0){
            JOptionPane.showMessageDialog(jPanel1, "escolha inválida! tente novamente", "AVISO!", JOptionPane.WARNING_MESSAGE);
        }
        else if (jComboBoxApagar.getSelectedIndex() == 1 && condApagar){
            // public pizza new blabla bla apagar com parametro vazio (tomara q de certo vsf)
            ListaPizza.pizzas[0] = new Pizza();
            mensagemApagar();
            taAvisos.setText("indice da remoção: 1");
            apagarCampos();
            cont = 0;
        }
        else if (jComboBoxApagar.getSelectedIndex() == 2 && condApagar) {
            ListaPizza.pizzas[1] = new Pizza();
            mensagemApagar();
            taAvisos.setText("indice da remoção: 2");
            apagarCampos();
            cont = 1;
        }
        else if (jComboBoxApagar.getSelectedIndex() == 3 && condApagar) {
            ListaPizza.pizzas[2] = new Pizza();
            mensagemApagar();
            taAvisos.setText("indice da remoção: 3");
            apagarCampos();
            cont = 2;
        }
        else if (jComboBoxApagar.getSelectedIndex() == 4 && condApagar) {
            ListaPizza.pizzas[3] = new Pizza();
            mensagemApagar();
            taAvisos.setText("indice de remoção: 4");
            apagarCampos();
            cont = 3;
        }
        else if (jComboBoxApagar.getSelectedIndex() == 5 && condApagar){
            ListaPizza.pizzas[4] = new Pizza();
            mensagemApagar();
            taAvisos.setText("indice de remoção:  5");
            apagarCampos();
            cont = 4;
        }
        jComboBoxApagar.setSelectedIndex(0);
    }//GEN-LAST:event_jComboBoxApagarActionPerformed

    private void jComboBoxApagarComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_jComboBoxApagarComponentShown
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBoxApagarComponentShown

    
    public void inserirObjeto(){
         Random numid = new Random();
        if (jTextFieldSabor.getText().length() != 0 && (jCheckBoxRecheioTRUE.isSelected() || jCheckBoxRecheioFALSE.isSelected())
                && (jCheckBoxAzeitonaTRUE.isSelected() || jCheckBoxAzeitonaFALSE.isSelected()) && jTextFieldFormato1.getText().length() != 0
                && jTextFieldPreco.getText().length() != 0 && jTextFieldPreco.getText().matches("^[0-9]*$")) {
            if (cont < ListaPizza.pizzas.length) {
                ListaPizza.pizzas[cont] = new Pizza(jTextFieldSabor.getText(), borda, jTextFieldPreco.getText(), azeitona,
                        jTextFieldFormato1.getText());
                ListaPizza.pizzas[cont].setId(numid.nextInt((10000 - 1000) + 1) + 100);
                String idstring = Integer.toString(ListaPizza.pizzas[cont].getId());
                jTextFieldID.setText(idstring);
                System.out.println(ListaPizza.pizzas[cont].toString());
                condApagar = true;
                taAvisos.setText("pizza " + (cont + 1) + " adicionada!");
                cont++;
                apagarCampos();
            } else {
                taAvisos.setText("Numero total atingido!\nredefinindo a ultima pizza...\npizza 5 adicionada!");
                ListaPizza.pizzas[4] = new Pizza(jTextFieldSabor.getText(), borda, jTextFieldPreco.getText(), azeitona,
                        jTextFieldFormato1.getText());
                ListaPizza.pizzas[4].setId(numid.nextInt((10000 - 1000) + 1) + 100);
                String idstring2 = Integer.toString(ListaPizza.pizzas[4].getId());
                jTextFieldID.setText(idstring2);
                System.out.println(ListaPizza.pizzas[4].toString());
                condApagar = true;
                apagarCampos();
            }
        }
        else {
            JOptionPane.showMessageDialog(jPanel1, "valores invalidos! tente novamente preenchendo todos os campos de forma correta!", "AVISO!", JOptionPane.WARNING_MESSAGE);
        }
    }
    
    public static void atribuirIdsString(){
        stpizzaid1 = Integer.toString(ListaPizza.pizzas[0].getId());
        stpizzaid2 = Integer.toString(ListaPizza.pizzas[1].getId());
        stpizzaid3 = Integer.toString(ListaPizza.pizzas[2].getId());
        stpizzaid4 = Integer.toString(ListaPizza.pizzas[3].getId());
        stpizzaid5 = Integer.toString(ListaPizza.pizzas[4].getId());
        if (ListaPizza.pizzas[0].getId() == 0){
            stpizzaid1 = "id vazio";
        }
        if (ListaPizza.pizzas[1].getId() == 0){
            stpizzaid2 = "id vazio";
        }
        if (ListaPizza.pizzas[2].getId() == 0) {
            stpizzaid3 = "id vazio";
        }
        if (ListaPizza.pizzas[3].getId() == 0){
            stpizzaid4 = "id vazio";
        }
        if (ListaPizza.pizzas[4].getId() == 0){
            stpizzaid5 = "id vazio";
        }
    }
    
    private void jComboBoxApagarFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jComboBoxApagarFocusGained
        try{
        // transformar todos os ids em string pra redefinir os itens do jComboBoxApagar
        atribuirIdsString();
        jComboBoxApagar.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Apagar", stpizzaid1, 
             stpizzaid2, stpizzaid3, stpizzaid4, stpizzaid5}));}
        catch (NullPointerException error){
            System.out.print("");
        }
    }//GEN-LAST:event_jComboBoxApagarFocusGained

    private void jComboBoxEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxEditarActionPerformed
        try {
            if (jComboBoxEditar.getSelectedIndex() == 0) {
                JOptionPane.showMessageDialog(jPanel1, "escolha inválida! tente novamente", "AVISO!", JOptionPane.WARNING_MESSAGE);

            } else if (jComboBoxEditar.getSelectedIndex() == 1) {
                //JOptionPane.showMessageDialog(jPanel1,"teste", "oi", JOptionPane.ERROR_MESSAGE);
                taAvisos.setText("Editando pizza 1 ! \nid: " + ListaPizza.pizzas[0].getId()); //ListaPizza.pizzas[0].getId());
            }
        }
        catch (NullPointerException error){
            System.out.println("");
        }
    }//GEN-LAST:event_jComboBoxEditarActionPerformed

    private void jComboBoxEditarFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jComboBoxEditarFocusGained
        try{
            // transformar ids em string pro botao de editar
            atribuirIdsString();
            jComboBoxEditar.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Editar", stpizzaid1, 
             stpizzaid2, stpizzaid3, stpizzaid4, stpizzaid5}));
        }
        catch (NullPointerException error) {
            System.out.println("");
        }
    }//GEN-LAST:event_jComboBoxEditarFocusGained

    private void jComboBoxMostrarDadosFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jComboBoxMostrarDadosFocusGained
        try{
            atribuirIdsString();
            jComboBoxMostrarDados.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Visualizar", stpizzaid1, 
             stpizzaid2, stpizzaid3, stpizzaid4, stpizzaid5}));
        }
        catch (NullPointerException error){
            System.out.println("");
        }
    }//GEN-LAST:event_jComboBoxMostrarDadosFocusGained
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(InterfacePizza.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(InterfacePizza.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(InterfacePizza.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(InterfacePizza.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        
        
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new InterfacePizza().setVisible(true);
            }
        }
        );
        
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Titulo;
    private javax.swing.JButton jButtonAdicionar1;
    private javax.swing.JCheckBox jCheckBoxAzeitonaFALSE;
    private javax.swing.JCheckBox jCheckBoxAzeitonaTRUE;
    private javax.swing.JCheckBox jCheckBoxRecheioFALSE;
    private javax.swing.JCheckBox jCheckBoxRecheioTRUE;
    private javax.swing.JComboBox<String> jComboBoxApagar;
    private javax.swing.JComboBox<String> jComboBoxEditar;
    private javax.swing.JComboBox<String> jComboBoxMostrarDados;
    private javax.swing.JLabel jLabelAzeitona;
    private javax.swing.JLabel jLabelAzeitona11;
    private javax.swing.JLabel jLabelBorda;
    private javax.swing.JLabel jLabelFormato;
    private javax.swing.JLabel jLabelID;
    private javax.swing.JLabel jLabelPreco;
    private javax.swing.JLabel jLabelRecheio;
    private javax.swing.JLabel jLabelRecheio2;
    private javax.swing.JLabel jLabelRecheio3;
    private javax.swing.JLabel jLabelSabor;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanelBorda;
    private javax.swing.JPanel jPanelBorda1;
    private javax.swing.JPanel jPanelBorda2;
    private javax.swing.JPanel jPanelBorda22;
    private javax.swing.JPanel jPanelBorda23;
    private javax.swing.JPanel jPanelBorda3;
    private javax.swing.JPanel jPanelID;
    private javax.swing.JPanel jPanelSabor;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jTextFieldFormato1;
    private javax.swing.JTextField jTextFieldID;
    private javax.swing.JTextField jTextFieldPreco;
    private javax.swing.JTextField jTextFieldSabor;
    private javax.swing.JTextArea taAvisos;
    // End of variables declaration//GEN-END:variables
}
